os: osx
osx_image: xcode11.4
language: swift
install:
  - bundle install
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then fastlane tests; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then fastlane beta; fi'